---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Ceph packages
  apt:
    name: "{{ ceph_packages }}"
    state: present

- name: Create Ceph configuration directory
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'

- name: Create Ceph configuration file
  template:
    src: ceph.conf.j2
    dest: "{{ ceph_conf_file }}"
    mode: '0644'
  when: ceph_fsid != "" and ceph_mon_hosts | length > 0

- name: Create Ceph client keyring file
  template:
    src: ceph.keyring.j2
    dest: "{{ ceph_keyring_file }}"
    mode: '0600'
