---
galaxy_info:
  author: CloudRift AI
  description: Install and configure libvirt/virsh with RBD support
  company: CloudRift AI
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - libvirt
    - virtualization
    - kvm
    - qemu
    - rbd

dependencies: []
