---
# Ceph cluster configuration for us_east_nc_nr_1
ceph_fsid: "b3b7a78d-a821-11f0-a8bc-bc24115dacb3"

ceph_mon_hosts:
  - "[v2:142.214.185.181:3300/0,v1:142.214.185.181:6789/0]"
  - "[v2:142.214.185.182:3300/0,v1:142.214.185.182:6789/0]"
  - "[v2:142.214.185.183:3300/0,v1:142.214.185.183:6789/0]"

ceph_client_name: "client.admin"
ceph_client_key: "{{ vault_ceph_client_key }}"
