$ANSIBLE_VAULT;1.1;AES256
65373966383531616632646336346466333838396630653165326535636661386564643562663830
3464316231623337303238376236373130393736323466350a343539363638343433356365636662
63336563626164346538313732376463633735383464353730386663376533336537343233333664
3833356663633135380a343565626433316331663933393731666364616663383032643235313933
35343738656261633238376662633462353639373534326263306134623135346433356235326362
64346637363661303536363165326136313662346233656532353965346238316363643661396563
65303035666662663936663663373838383536366263346636666661363634373233396561666361
36643865376563636336656132373435373734343237366562336335306539643134303636646336
35633939376237306438613435323030343639363232636438353230306632363064306336376331
62373138383134376562643764336264376536373634613964326562353632616135326430333132
62336461386164306537306230376361393837376238376639636265336534393761373839633065
62633531363463643239376266376463376131643366346134626266313631633662353031633236
64333235633034346363356165326535323862646132306361353539383464386536653638383866
3931373935326263616131336133626135333233623630636363
